---
title: "Lab3_ggplot"
author: "Dulla"
date: "2024-04-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
consumptionNoOil <- read.csv("consumptionNoOil.csv", header=T, stringsAsFactors=T)
```


```{r}
summary(consumptionNoOil)
```

```{r}
head(consumptionNoOil, 10)
```

```{r}
p <- ggplot(data= consumptionNoOil, aes(x=MTOE,y=EstMTOE))
p <- p + geom_point()
p
```
```{r}
p <- p + geom_point(colour= "darkgreen")
p
```
```{r}
p <- ggplot(consumptionNoOil, aes(MTOE, EstMTOE, colour=Source))
p <- p + geom_point()
p
```

```{r}
p <- ggplot(consumptionNoOil, aes(MTOE, EstMTOE, shape=Source))
p <- p + geom_point()
p
```
```{r}
p <- ggplot(consumptionNoOil, aes(MTOE, EstMTOE,
colour = Source, shape=Source))
p <- p + geom_point()
p
```
```{r}
p <- ggplot(consumptionNoOil, aes(Year, MTOE))
p <- p + geom_line()
p
```
```{r}
p <- ggplot(consumptionNoOil, aes(Year, MTOE, colour=Source))
p <- p + geom_line()
p
```

```{r}
p <- ggplot(consumptionNoOil, aes(Year, MTOE, group = Source))
p <- p + geom_line()
p
```

```{r}
p <- ggplot(consumptionNoOil, aes(Year, MTOE, group = Source))
p <- p + geom_line()
p
```

```{r}
p <- p + geom_line(size = 2, colour="darkgreen")
p
```
```{r}
p <- ggplot(consumptionNoOil, aes(Year, MTOE, group = Source))
p <- p + geom_point()
p
```

```{r}
p <- ggplot(consumptionNoOil, aes(Year, MTOE, group = Source))
p <- p + geom_point()
p <- p + geom_line()
p
```
```{r}
p <- p + geom_point(shape = 24, colour = "red", size = 4,
fill = "lightblue")
p
```
```{r}
p <- ggplot(consumptionNoOil, aes(Year, MTOE, group = Source))
p <- p + geom_line()
p <- p + geom_smooth(aes(group = 1), formula='y~x',
method = "lm", size = 2, se = F)
p
```
```{r}
ProvenOilReservesZerosT <- read.csv("ProvenOilReservesZerosT.csv",
header=T)
ProvenOilReservesZerosT
```

```{r}
ProvenOilReservesZerosT |>
mutate_all(funs(replace(., .== "-", as.double(NA))))
```
```{r}
YearlyProvenOil <- ggplot(data = ProvenOilReservesZerosT, aes(MTBarrels, Denmark ))
YearlyProvenOil <- YearlyProvenOil + geom_point()
YearlyProvenOil
```
```{r}
YearlyProvenOil <- ggplot(data = ProvenOilReservesZerosT, aes(MTBarrels, Denmark ))
YearlyProvenOil <- YearlyProvenOil + geom_point(shape=22, size=4, colors='darkblue', fill='blue')
YearlyProvenOil
```
```{r}
YearlyProvenOil <- ggplot(data = ProvenOilReservesZerosT, aes(MTBarrels, Italy ))
YearlyProvenOil <- YearlyProvenOil + geom_line(size=2, color='orange')
YearlyProvenOil
```
```{r}
YearlyProvenOil <- ggplot(data = ProvenOilReservesZerosT, aes(MTBarrels, United.Kingdom ,alpha=MTBarrels))
YearlyProvenOil <- YearlyProvenOil + geom_point(size=2, colors=source)
YearlyProvenOil
```

```{r}
ProvenOilReserveWEurope<- read.csv('ProvenOilReserveWEurope.csv', header = T, stringsAsFactors = T)
to1990 <- ProvenOilReserveWEurope |> filter(Year %in% c(1980:1990))
summary(to1990)
```


```{r}
p <- ggplot(ProvenOilReservesZerosT, aes(MTBarrels, United.Kingdom))
p <- p + geom_point(aes(colour=United.Kingdom))
p
```


```{r}
p <- ggplot(to1990, aes(Year, Country))
p <- p+ geom_tile(aes(alpha=MT.Barrels), fill= "blue")
p
```
```{r}
to2001 <- ProvenOilReserveWEurope |>
  filter(Year %in% c(1990:2001))
summary(to2001)
```

```{r}
p <- ggplot(data = to2001, aes(Year, Country))
p <- p + geom_tile(aes(alpha=MT.Barrels), fill='red')
p
```
```{r}
p <- ggplot(ProvenOilReservesZerosT, aes(MTBarrels, Norway, size=Norway))
p <- p + geom_point(shape=24, colour="red")
p
```

```{r}
p <- ggplot(ProvenOilReserveWEurope, aes(Year, MT.Barrels, group=Country, alpha=Country))
p <- p + geom_line()
p
```

```{r}
p <- ggplot(ProvenOilReserveWEurope, aes(Year, MT.Barrels, group=Country, color=Country))
p <- p + geom_line()
p <- p + geom_smooth(aes(group = 1), formula = y~x, method = "lm", size = 2, se = F)
p
```

```{r}
p <- ggplot(ProvenOilReserveWEurope, aes(Year, MT.Barrels, group=Country,  colour=Country))
p <- p + geom_point()
p <- p + geom_smooth(aes(group = 1), formula = y~x,  method = "auto", se = F)
p
```